name: "Carbonoz SolarAutopilot"
description: "CARBONOZ SolarAutopilot on Homeassistant runs in a Docker container and will be offered in the Homeassistant Addon store for download. It includes a live Solar dashboard similiar to Solar Assistant project and allows inverter changes over MQTT."
version: "1.0.0"
slug: "carbonoz_solarautopilot"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
ingress: true
ingress_port: 6789
panel_icon: mdi:solar-power
panel_title: Carbonoz SolarAutopilot
hassio_api: true
ports:
  6789/tcp: 6789
  3000/tcp: 3000 # Grafana port
options:
  mqtt_ip: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  battery_number: 1
  inverter_number: 1
schema:
  mqtt_ip: str
  mqtt_port: port
  mqtt_username: str
  mqtt_password: password
  battery_number: int
  inverter_number: int
map:
  - "ssl"
